name: Build Release Zip

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create zip
        run: |
          cd "$GITHUB_WORKSPACE"
          zip -qr "it-drive-${GITHUB_REF_NAME}.zip" it-tool
          cp "it-drive-${GITHUB_REF_NAME}.zip" "it-drive-latest.zip"
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            it-drive-${{ github.ref_name }}.zip
            it-drive-latest.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
